// The judgments Jev makes about a post, and how code turns them into one probability.
// Pure module: no chrome APIs, so the Node scripts import it too.

// Pinned, not an alias: fitted weights and the threshold are tied to one model version.
export const JEV_MODEL = 'jev-1.13.0';
// Jev bills input tokens only. Output tokens are free. Price for the pinned model.
export const JEV_USD_PER_MILLION_INPUT_TOKENS = 0.042;

export function requestCostUsd(inputTokens) {
  return (inputTokens / 1_000_000) * JEV_USD_PER_MILLION_INPUT_TOKENS;
}

const TYPE = Object.freeze({ NOUL: 'noul', SCORE: 'score' });

// Each question is one narrow, literal judgment. Jev reads the words as written, so
// every instruction names the exact condition and gives examples of the pattern.
// Score levels run from least to most AI-like, so every feature points the same way.
// `needsParent` questions are only asked when the replied-to post is known.
export const QUESTIONS = Object.freeze({
  holistic_ai: {
    type: TYPE.NOUL,
    instructions:
      'Was `post.text` generated by an AI language model such as ChatGPT, rather than typed by a person?',
    criteria: {
      true: 'Reads like chatbot output: fluent, generic, evenly polished, with no personal quirks.',
      false: 'Reads like a person typed it: uneven, specific, opinionated, or idiosyncratic.',
    },
  },
  contrast_frame: {
    type: TYPE.NOUL,
    instructions:
      "Does `post.text` use a 'not X, but Y' contrast frame, such as \"It's not just X, it's Y\" or \"This isn't about X. It's about Y.\"?",
  },
  opens_with_praise: {
    type: TYPE.NOUL,
    instructions:
      "Does `post.text` open by praising or agreeing with another post, such as 'Great point', 'Love this', 'This is spot on', or 'Absolutely'?",
  },
  engagement_question: {
    type: TYPE.NOUL,
    instructions:
      "Does `post.text` end with a generic question meant to prompt replies, such as 'What do you think?' or 'Curious how others handle this?'",
  },
  stock_phrases: {
    type: TYPE.NOUL,
    instructions:
      "Does `post.text` use inflated stock phrases common in chatbot writing, such as 'game-changer', 'delve', 'a testament to', 'in today's fast-paced world', 'unlock', 'elevate', or 'navigate the landscape'?",
  },
  rule_of_three: {
    type: TYPE.NOUL,
    instructions:
      "Does `post.text` contain a list of three parallel words or phrases, such as 'fast, simple, and reliable'?",
  },
  aphorism_close: {
    type: TYPE.NOUL,
    instructions:
      "Does `post.text` end with a short punchy moral that sums up the post, such as 'Consistency beats talent.' or 'That's the real unlock.'?",
  },
  mini_essay_format: {
    type: TYPE.NOUL,
    instructions:
      'Is `post.text` laid out like a structured mini-essay: a hook line, then one-sentence paragraphs or a bulleted or numbered list, then a takeaway?',
  },
  balanced_stance: {
    type: TYPE.NOUL,
    instructions:
      'Does `post.text` take a careful, inoffensive stance that acknowledges both sides instead of stating a strong personal opinion?',
  },
  announcement_hype: {
    type: TYPE.NOUL,
    instructions:
      "Does `post.text` announce news with stock emotional framing, such as 'I'm thrilled to announce', 'Excited to share', or 'Humbled and honored'?",
  },
  insight_reframe: {
    type: TYPE.NOUL,
    instructions:
      "Does `post.text` reframe its topic as a hidden insight, using a frame such as 'the hard part is...', 'the real work is...', 'what most people miss is...', 'the invisible half is still work', or 'X is actually Y'?",
    criteria: {
      true: 'It states, in general terms, what the hard part, the real work, the actual problem, or the overlooked piece of the topic is, and presents that as the deeper truth.',
      false: "It reports what happened, asks something, jokes, or gives an opinion without presenting it as a deeper truth others overlook. A concrete account is false even with one of those phrases, such as 'the hard part was the visa, it took nine months'.",
    },
  },
  unearned_real: {
    type: TYPE.NOUL,
    instructions:
      "Does `post.text` describe something as 'real', such as 'the real lesson', 'the real issue', or 'the real work', without mentioning any false, fake, or surface version of that thing to contrast it with?",
    criteria: {
      true: "The word 'real' could be deleted with no change in meaning, because no other version of the thing is mentioned anywhere in `post.text`.",
      false: "`post.text` does not describe anything as 'real'. Or it names the version it contrasts with, such as 'everyone blames pricing, but the real issue is distribution'. Or 'real' is part of a fixed term such as 'real estate', 'real-time', or 'for real'.",
    },
  },
  generic_lesson: {
    type: TYPE.NOUL,
    needsParent: true,
    instructions:
      "Does `post.text` turn `parent.text` into a general lesson that would fit as a reply to almost any post on a similar topic, such as 'a good reminder that...', 'the real lesson here is...', or 'the harder part is...'?",
    criteria: {
      true: 'It states a broad takeaway about business, work, or life and does not engage with the specific facts, numbers, or claims in `parent.text`.',
      false: 'It responds to something specific in `parent.text`: a fact, a number, a named person or company, a claim it agrees or disagrees with, or a question it asks about it.',
    },
  },
  restates_parent: {
    type: TYPE.NOUL,
    needsParent: true,
    instructions:
      'Does `post.text` mostly restate or summarize `parent.text` in different words, adding only praise or a general observation?',
  },
  ignores_parent_detail: {
    type: TYPE.NOUL,
    needsParent: true,
    instructions:
      'Could `post.text` be posted unchanged under many unrelated posts, because it engages with no specific detail of `parent.text`?',
  },
  generic_content: {
    type: TYPE.SCORE,
    instructions: 'How generic is the content of `post.text`?',
    criteria: [
      'Concrete firsthand detail: specific people, places, numbers, events, or experiences only the author would know.',
      'Some concrete detail mixed with general statements.',
      'Only general statements that anyone could write without firsthand knowledge.',
      'Entirely abstract platitudes or motivational generalities.',
    ],
  },
  polish: {
    type: TYPE.SCORE,
    instructions: 'How polished and edited is the writing in `post.text`?',
    criteria: [
      'Casual: typos, all lowercase, slang, fragments, abbreviations, or run-on sentences.',
      'Conversational, with mostly correct grammar and punctuation.',
      'Fully correct grammar and punctuation in complete, balanced sentences.',
      'Essay-like: formal, carefully structured sentences that read like edited marketing or corporate copy.',
    ],
  },
  missing_voice: {
    type: TYPE.SCORE,
    instructions: 'How much personal voice does `post.text` show?',
    criteria: [
      'Strong personal voice: humor, sarcasm, anger, in-jokes, or idiosyncratic phrasing.',
      'Some personality, but mostly plain.',
      'Neutral and impersonal, like a press release or a customer-service reply.',
    ],
  },
});

// Patterns code can detect exactly stay in code.
const CODE_FEATURES = Object.freeze({
  em_dash: (text) => (text.includes('—') ? 1 : 0),
  all_lowercase: (text) => (/[a-z]/.test(text) && !/[A-Z]/.test(text) ? 1 : 0),
  // Three or more lines that each open with an emoji used as a bullet.
  emoji_bullets: (text) => ((text.match(/^\s*\p{Extended_Pictographic}/gmu) ?? []).length >= 3 ? 1 : 0),
  // Three or more hashtags stacked at the end of the post.
  hashtag_pile: (text) => (/(#[\p{L}\p{N}_]+\s*){3,}$/u.test(text.trim()) ? 1 : 0),
});

// Hand-set starting point. Replace with the output of scripts/fit.mjs once labels exist.
export const DEFAULT_WEIGHTS = Object.freeze({
  bias: -5.5,
  w: Object.freeze({
    holistic_ai: 2.5,
    contrast_frame: 1.2,
    opens_with_praise: 0.8,
    engagement_question: 0.8,
    stock_phrases: 1.0,
    rule_of_three: 0.5,
    aphorism_close: 0.8,
    mini_essay_format: 0.6,
    balanced_stance: 0.5,
    announcement_hype: 0.8,
    insight_reframe: 2.0,
    unearned_real: 0.8,
    generic_lesson: 1.2,
    restates_parent: 1.0,
    ignores_parent_detail: 1.0,
    generic_content: 1.5,
    polish: 1.2,
    missing_voice: 1.5,
    em_dash: 0.6,
    all_lowercase: -1.0,
    emoji_bullets: 0.6,
    hashtag_pile: 0.4,
  }),
});

export function buildState(post) {
  const state = { post: { text: post.text } };
  if (post.parentText) state.parent = { text: post.parentText };
  return state;
}

export function buildQuestions(post) {
  const questions = {};
  for (const [id, { needsParent, ...question }] of Object.entries(QUESTIONS)) {
    if (needsParent && !post.parentText) continue;
    questions[id] = question;
  }
  return questions;
}

function readAnswer(question, answer) {
  if (!answer) return 0;
  if (question.type === TYPE.NOUL) return answer.noul;
  return answer.score / (question.criteria.length - 1);
}

// Every feature lands on 0..1. Questions that were not asked read as 0.
export function featureVector(answers, post) {
  const features = {};
  for (const [id, question] of Object.entries(QUESTIONS)) {
    features[id] = readAnswer(question, answers[id]);
  }
  for (const [id, detect] of Object.entries(CODE_FEATURES)) {
    features[id] = detect(post.text);
  }
  return features;
}

// Why a post got its score: every feature's pull on it, strongest first.
// `askedIds` are the questions that were sent. A reply-only question that was not sent
// reads as 0, and the breakdown says so instead of showing it as a "no".
export function explain(features, weights = DEFAULT_WEIGHTS, askedIds = Object.keys(QUESTIONS)) {
  const asked = new Set(askedIds);
  const rows = Object.entries(features).map(([id, value]) => {
    const weight = weights.w[id] ?? 0;
    return { id, value, weight, contribution: weight * value, asked: !(id in QUESTIONS) || asked.has(id) };
  });
  rows.sort((a, b) => Math.abs(b.contribution) - Math.abs(a.contribution));
  return { bias: weights.bias, rows };
}

export function sigmoid(z) {
  return 1 / (1 + Math.exp(-z));
}

export function probability(features, weights = DEFAULT_WEIGHTS) {
  let z = weights.bias;
  for (const [id, value] of Object.entries(features)) {
    z += (weights.w[id] ?? 0) * value;
  }
  return sigmoid(z);
}
