// The judgments Jev makes about a tweet, and how code turns them into one probability.
// Pure module: no chrome APIs, so the Node scripts import it too.

// Pinned, not an alias: fitted weights and the threshold are tied to one model version.
export const JEV_MODEL = 'jev-1.13.0';

const TYPE = Object.freeze({ NOUL: 'noul', SCORE: 'score' });

// Each question is one narrow, literal judgment. Jev reads the words as written, so
// every instruction names the exact condition and gives examples of the pattern.
// Score levels run from least to most AI-like, so every feature points the same way.
// `needsParent` questions are only asked when the replied-to post is known.
export const QUESTIONS = Object.freeze({
  holistic_ai: {
    type: TYPE.NOUL,
    instructions:
      'Was `tweet.text` generated by an AI language model such as ChatGPT, rather than typed by a person?',
    criteria: {
      true: 'Reads like chatbot output: fluent, generic, evenly polished, with no personal quirks.',
      false: 'Reads like a person typed it: uneven, specific, opinionated, or idiosyncratic.',
    },
  },
  contrast_frame: {
    type: TYPE.NOUL,
    instructions:
      "Does `tweet.text` use a 'not X, but Y' contrast frame, such as \"It's not just X, it's Y\" or \"This isn't about X. It's about Y.\"?",
  },
  opens_with_praise: {
    type: TYPE.NOUL,
    instructions:
      "Does `tweet.text` open by praising or agreeing with another post, such as 'Great point', 'Love this', 'This is spot on', or 'Absolutely'?",
  },
  engagement_question: {
    type: TYPE.NOUL,
    instructions:
      "Does `tweet.text` end with a generic question meant to prompt replies, such as 'What do you think?' or 'Curious how others handle this?'",
  },
  stock_phrases: {
    type: TYPE.NOUL,
    instructions:
      "Does `tweet.text` use inflated stock phrases common in chatbot writing, such as 'game-changer', 'delve', 'a testament to', 'in today's fast-paced world', 'unlock', 'elevate', or 'navigate the landscape'?",
  },
  rule_of_three: {
    type: TYPE.NOUL,
    instructions:
      "Does `tweet.text` contain a list of three parallel words or phrases, such as 'fast, simple, and reliable'?",
  },
  aphorism_close: {
    type: TYPE.NOUL,
    instructions:
      "Does `tweet.text` end with a short punchy moral that sums up the post, such as 'Consistency beats talent.' or 'That's the real unlock.'?",
  },
  mini_essay_format: {
    type: TYPE.NOUL,
    instructions:
      'Is `tweet.text` laid out like a structured mini-essay: a hook line, then one-sentence paragraphs or a bulleted or numbered list, then a takeaway?',
  },
  balanced_stance: {
    type: TYPE.NOUL,
    instructions:
      'Does `tweet.text` take a careful, inoffensive stance that acknowledges both sides instead of stating a strong personal opinion?',
  },
  restates_parent: {
    type: TYPE.NOUL,
    needsParent: true,
    instructions:
      'Does `tweet.text` mostly restate or summarize `parent.text` in different words, adding only praise or a general observation?',
  },
  ignores_parent_detail: {
    type: TYPE.NOUL,
    needsParent: true,
    instructions:
      'Could `tweet.text` be posted unchanged under many unrelated posts, because it engages with no specific detail of `parent.text`?',
  },
  generic_content: {
    type: TYPE.SCORE,
    instructions: 'How generic is the content of `tweet.text`?',
    criteria: [
      'Concrete firsthand detail: specific people, places, numbers, events, or experiences only the author would know.',
      'Some concrete detail mixed with general statements.',
      'Only general statements that anyone could write without firsthand knowledge.',
      'Entirely abstract platitudes or motivational generalities.',
    ],
  },
  polish: {
    type: TYPE.SCORE,
    instructions: 'How polished and edited is the writing in `tweet.text`?',
    criteria: [
      'Casual: typos, all lowercase, slang, fragments, abbreviations, or run-on sentences.',
      'Conversational, with mostly correct grammar and punctuation.',
      'Fully correct grammar and punctuation in complete, balanced sentences.',
      'Essay-like: formal, carefully structured sentences that read like edited marketing or corporate copy.',
    ],
  },
  missing_voice: {
    type: TYPE.SCORE,
    instructions: 'How much personal voice does `tweet.text` show?',
    criteria: [
      'Strong personal voice: humor, sarcasm, anger, in-jokes, or idiosyncratic phrasing.',
      'Some personality, but mostly plain.',
      'Neutral and impersonal, like a press release or a customer-service reply.',
    ],
  },
});

// Patterns code can detect exactly stay in code.
const CODE_FEATURES = Object.freeze({
  em_dash: (text) => (text.includes('—') ? 1 : 0),
  all_lowercase: (text) => (/[a-z]/.test(text) && !/[A-Z]/.test(text) ? 1 : 0),
});

// Hand-set starting point. Replace with the output of scripts/fit.mjs once labels exist.
export const DEFAULT_WEIGHTS = Object.freeze({
  bias: -5.5,
  w: Object.freeze({
    holistic_ai: 2.5,
    contrast_frame: 1.2,
    opens_with_praise: 0.8,
    engagement_question: 0.8,
    stock_phrases: 1.0,
    rule_of_three: 0.5,
    aphorism_close: 0.8,
    mini_essay_format: 0.6,
    balanced_stance: 0.5,
    restates_parent: 1.0,
    ignores_parent_detail: 1.0,
    generic_content: 1.5,
    polish: 1.2,
    missing_voice: 1.5,
    em_dash: 0.6,
    all_lowercase: -1.0,
  }),
});

export function buildState(tweet) {
  const state = { tweet: { text: tweet.text } };
  if (tweet.parentText) state.parent = { text: tweet.parentText };
  return state;
}

export function buildQuestions(tweet) {
  const questions = {};
  for (const [id, { needsParent, ...question }] of Object.entries(QUESTIONS)) {
    if (needsParent && !tweet.parentText) continue;
    questions[id] = question;
  }
  return questions;
}

function readAnswer(question, answer) {
  if (!answer) return 0;
  if (question.type === TYPE.NOUL) return answer.noul;
  return answer.score / (question.criteria.length - 1);
}

// Every feature lands on 0..1. Questions that were not asked read as 0.
export function featureVector(answers, tweet) {
  const features = {};
  for (const [id, question] of Object.entries(QUESTIONS)) {
    features[id] = readAnswer(question, answers[id]);
  }
  for (const [id, detect] of Object.entries(CODE_FEATURES)) {
    features[id] = detect(tweet.text);
  }
  return features;
}

export function sigmoid(z) {
  return 1 / (1 + Math.exp(-z));
}

export function probability(features, weights = DEFAULT_WEIGHTS) {
  let z = weights.bias;
  for (const [id, value] of Object.entries(features)) {
    z += (weights.w[id] ?? 0) * value;
  }
  return sigmoid(z);
}
